### ISSUE TITLE
Users are displayed more than once

### ISSUE THREAD

**Issue by wbonekamp** [ChrisHammond/dnnCHAT#37]
the users that login to the chat are displayed more than once
![chatusers](https://cloud.githubusercontent.com/assets/7567981/4840708/98d27d46-6012-11e4-9d2e-b9b8da742028.JPG)

**Comment by ChrisHammond** [comment]
Recommendation would be to grab the latest build in the /install folder here on GitHub and see if you are still experiencing that problem. I believe this was fixed quite a while ago, just haven't done an official release yet.
