### ISSUE TITLE
Error When Installing

### ISSUE THREAD

**Issue by maduranga001** [ChrisHammond/dnnCHAT#41]
Hi,

I am using DNN 7.3 and DnnChat_01.00.00_Install module (dnnCHAT V1.1.0 for DNN 7.1 using SignalR) you released on Wed Jun 18, 2014 at 8:00 AM

But I can not install the module on my site and giving this error.

A dependent component is not installed - System.Reflection.ReflectionContext

How can I fix this? How can i install this? Please advise.

Thank You!

**Comment by ChrisHammond** [comment]
You need to ensure you have .net 4.5 installed on the server

**Comment by maduranga001** [comment]
Thank You chris. Yes I installed the module in another server which has 4.5 and working fine. Thank you for your answer and for the support.

I need use this module as a shoutbox module.
In other way, it is available and can write only for registered users in the site and the module is using the same username/display name for the login.
So they do not want to login again and all users are in one chat as a group chat.
 Is this possible to do? 
Please can you advise?

**Comment by ChrisHammond** [comment]
I don't know what a shoutbox module is, but if you want to limit who can use the module you would do that through normal module or page permissions.

As for if they use a displayname/username, that is all configured in DNN's registration/user settings

**Comment by maduranga001** [comment]
Hello Chris. 

Thank you for the reply.

1) I need to see the chat conversation for all users including unregistered users. But I need to give access to send messages only for registered users. How can I do this?

2) I can see there is a one chatroom called "Lobby" . I need only one and do not need to allow to create more chat rooms or give more chat rooms for now. Anyway how I can create new chat rooms and how can I allow to send messages only for registered users?

3) Can I minimize the chat window? Width and height?

4) Is there a way to send Private message? Then I can send you a testing link.

5) Don't I have the feature to pick colors from the color picker and the smilies? 

6) I can see the it has a link under the module - "Powered by the dnnCHAT module for DotNetNuke, from Christoc.com". Can't I remove this? I know it is not nice for you. But as I am using this module in the moddle of the site, not sure my client will allow for that.

Please can you advise me? Appreciate your support and for the great module.

Thank You!

**Comment by ChrisHammond** [comment]
All of those things are possible, but not currently features in the module. You would either 

a) need to fork and create your own distribution of the module
b) make those changes and submit a PULL request back to github to have the changes included in the open source version
c) pay someone to make those changes for you (going down either A or B as well)

**Comment by maduranga001** [comment]
Ok Chris. Thank You!

How can I create new Rooms?
How can I limit the number of messages avaialable in the screen? Is there a default number?

Thank you for your support.

**Comment by ChrisHammond** [comment]
New rooms are created by typing "/room New Name" into the chat window. YOu need to be logged in to do this.

There is a new package in source code, not actually released, that allows you to manage rooms through the module settings as well.

There is no limit to number of messages at this time. I believe it only pulls back the last 50 though when you connect. That is not an exposed setting.

**Comment by maduranga001** [comment]
Great! Thanks!

Please can you give me the PA installation version for the last release? I really appreciate this.
Tahnk You!

**Comment by maduranga001** [comment]
Hi Chris,

Between how can I delete a room once I add it? 
It seems fine to use this module for my requirements apart from one thing. It shhould't allow to send messages to the unregistered users. But They should see the conversations. If you have any ideas, please help.

I really appreciate if you can give me the PA installation version with your last canges. This page has only the source for your module. 

Thank you very much for your support.

**Comment by ChrisHammond** [comment]
the versions are all available at https://github.com/ChrisHammond/dnnCHAT/tree/master/install

Rooms can be deleted/disabled through the UI in the latest INSTALL package  https://github.com/ChrisHammond/dnnCHAT/blob/master/install/DnnChat_01.01.01_Install.zip

click the "raw" link on that page

**Comment by maduranga001** [comment]
Hi Chris,

I am using 01.01.01 version now. Thank you for giving it.

1) I need to allow only for some user role or a set of specific users a one chat room. I did try with the password option too and it is not working. Please can you tell me if there's any other ways to do this with the current version?

2) I do not need default "Lobby" chat room. Can I delete it without just only desabling it? If I desable it and change to another chat room as athe default one in the settings, the entire module is not working.

Please can you advise me.

Thank You!
