### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by maduranga001** [ChrisHammond/dnnCHAT#42]
Hi,

The module is not loading or isplaying in the mobile sites. I am using Android Galaxy S3 and tested the module is not display or working eben with a strong WiFi connection.

I am using your latest modules.
Please can you advise about this please? The module is working in computers well and than you very mucj for your great module.

Thank You!

**Comment by ChrisHammond** [comment]
I just checked in new code that uses (requires) bootstrap to work on mobile devices. I will be doing a release sometime in the next few weeks for this officially, but you can grab the latest ZIP from the /install folder and install that if you want.

**Comment by maduranga001** [comment]
Hi,

I grab the zip file from /install folder and installed. But still it is not working on mobile devices.
I am using DnnChat_02.00.00_Install.zip from there.

Please can you advise for this?
Thank You!

**Comment by ChrisHammond** [comment]
You need to have a Bootstrap skin applied to your site as well.

**Comment by maduranga001** [comment]
Hi Chris,

I am using a custom DNN skin.
So please can you tell me how to do this?

Thank You!

**Comment by ChrisHammond** [comment]
Yes, download my HammerFlex skin, use that.
