### ISSUE TITLE
DNNChat module doesn't work correctly! see the attached image any help please

### ISSUE THREAD

**Issue by omarnoubani** [ChrisHammond/dnnCHAT#45]
![dnnchat](https://cloud.githubusercontent.com/assets/13849714/9328069/40007aa6-45ae-11e5-9f4f-8d5bb6e61f40.png)

**Comment by ChrisHammond** [comment]
What skin are you trying to install the module on? You'll need to make sure it is a bootstrap skin.

**Comment by omarnoubani** [comment]
Hi @ChrisHammond 
it's bootstrap skin
the curious case that it work correctly in another machine

**Comment by omarnoubani** [comment]
@ChrisHammond  i think that it doesn't read the records that exists in the room DNNChat_Rooms table

**Comment by ChrisHammond** [comment]
You will need to look and see what kind of Javascript errors you are getting, likely SignalR isn't loading properly. Or you need to go into the Module settings and configure the settings for the module and then try to load things.
