### ISSUE TITLE
9.4.1 Issues

### ISSUE THREAD

**Issue by ChrisHammond** [ChrisHammond/dnnCHAT#50]
Looks like you can't upgrade DNN 9.4.1 if you have the SignalR/Owin DLLs. Need to look at upgrading DNN Chat module to fix this. I'll hopefully be able to get on that soon.

**Comment by thabaum** [comment]
Looks like you are working on these issues.  I seen a 3.0.3 version release however there is not a download provided yet.  I am thinking of testing this module out on a DNN 9.5 site see if I can get it working ok.

**Comment by ChrisHammond** [comment]
You can grab the latest Install.zip file from

https://github.com/ChrisHammond/dnnCHAT/blob/master/install/DnnChat_03.00.04_Install.zip

click the DOWNLOAD option

**Comment by thabaum** [comment]
thank you.

**Comment by ChrisHammond** [comment]
I just put out a 03.00.05 release with a momentjs update
